---
title: jillande.github.io
timezone: America/Denver
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Jillande
description: Personal blog
url: https://jillande.github.io
paginate: 10
markdown: kramdown
permalink: pretty
